#!/usr/bin/env bash
# Boots the local Supabase stack for the e2e sync suite (e2e/sync.spec.ts) and
# writes .env.e2e with the local credentials the Playwright "sync" project
# needs. Requires Docker. Safe to re-run: it resets the local database so every
# test run starts from a clean schema.
set -euo pipefail
cd "$(dirname "$0")/.."

# The local stack applies supabase/migrations on start/reset, but the schema's
# single source of truth is db-structure.sql — mirror it (the copy is gitignored).
mkdir -p supabase/migrations
cp db-structure.sql supabase/migrations/00000000000000_schema.sql

if pnpm exec supabase status >/dev/null 2>&1; then
  # Stack already running: wipe data and reapply the schema.
  pnpm exec supabase db reset
else
  pnpm exec supabase start
fi

# `status -o env` prints KEY="value" lines; older/newer CLIs name the keys
# differently, so accept both spellings.
eval "$(pnpm exec supabase status -o env 2>/dev/null)"

API_URL="${API_URL:-}"
E2E_ANON_KEY="${ANON_KEY:-${PUBLISHABLE_KEY:-}}"
E2E_SERVICE_ROLE_KEY="${SERVICE_ROLE_KEY:-${SECRET_KEY:-}}"

if [[ -z "$API_URL" || -z "$E2E_ANON_KEY" || -z "$E2E_SERVICE_ROLE_KEY" ]]; then
  echo "error: could not read local credentials from 'supabase status -o env'" >&2
  exit 1
fi

case "$API_URL" in
  http://127.0.0.1:*|http://localhost:*) ;;
  *)
    echo "error: refusing non-local Supabase URL '$API_URL'" >&2
    exit 1
    ;;
esac

# The master key is test-only (the local DB is disposable); a fixed value keeps
# runs deterministic and debuggable.
cat > .env.e2e <<EOF
# Generated by scripts/e2e-sync-setup.sh — do not edit, do not commit.
NEXT_PUBLIC_SUPABASE_URL=$API_URL
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY=$E2E_ANON_KEY
E2E_SUPABASE_SERVICE_ROLE_KEY=$E2E_SERVICE_ROLE_KEY
ENCRYPTION_MASTER_KEY=a4Ilq6IQTeYCeIFsiUCtAOsSgcborzEt8mxQandI/BY=
EOF

echo
echo "Local Supabase ready. Run the sync suite with: pnpm test:e2e:sync"
